= YAML Schema Validator
:toc:
:toclevels: 3
:source-highlighter: prettify

image:https://img.shields.io/maven-central/v/org.alexmond/yj-schema-validator.svg?label=Maven%20Central[Maven Central,link=https://search.maven.org/artifact/yj-schema-validator]
image:https://img.shields.io/badge/License-Apache%202.0-blue.svg[License,link=LICENSE]
image:https://img.shields.io/github/actions/workflow/status/alexmond/yj-schema-validator/maven.yml[Build Status,link=https://github.com/alexmond/yj-schema-validator/actions]

A Java command line utility for validating YAML/JSON files against JSON schemas, built with Spring Boot.

== Features

* Validates YAML and JSON files against JSON Schema definitions
* Built on top of Spring Boot framework
* Support for Jackson YAML/JSON parsing
* Uses NetworkNT JSON Schema Validator
* Java 17+ compatible

== Getting Started

=== Building

To build the application:

[source,shell]
----
mvn clean package
----

=== Running

Run the validator using:

[source,shell]
----
java -jar target/yj-schema-validator.jar --file=<yaml/json_file> --schema=<schema_file>
----

Or validate multiple files:

[source,shell]
----
java -jar target/yj-schema-validator.jar file1.yaml file2.yaml --schema=schema.json
----

=== Usage Examples

.Validate a single YAML file
[source,shell]
----
java -jar yj-schema-validator.jar --file=config.yaml --schema=schema.json
----

.Validate multiple YAML files
[source,shell]
----
java -jar yj-schema-validator.jar config1.yaml config2.yaml --schema=schema.json
----

=== Configuration Options

[cols="1,2"]
|===
|Option |Description

|--file
|Path to YAML/JSON file to validate (can be specified multiple times)

|--schema
|Path to JSON Schema file for validation
|===
