name: Java CI with Maven
on: [push, manual]
push:
  branches: [main]
jobs:
  build:
    image: eclipse-temurin:17-jdk
    cache:
      key: m2-yj-schema-validator
      paths: [.m2/repository]
    steps:
      - name: Checkout
        run: git clone --depth 1 https://github.com/alexmond/yj-schema-validator.git .
      - name: Build with Maven
        run: ./mvnw -B package --file pom.xml -Pdefault --no-transfer-progress -Dmaven.repo.local=.m2/repository
