name: Validate JSON with check-jsonschema

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install check-jsonschema
        run: pip install check-jsonschema

      - name: Run validation and generate JSON report
        run: |
          check-jsonschema \
            --schemafile src/test/resources/sample-schema.json \
            src/test/resources/*json \
            -o JSON > validation-report.json | true

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            validation-report.json
